### ISSUE TITLE
Restore colour

### ISSUE THREAD

**Issue by grahamperrin** [xia-sava/Monochromer#1]
### Enhancement request

A second click on the toolbar icon should restore colour (cease the greyscale view).

**Comment by xia-sava** [comment]
お，おう，あたしもそう思ってました……実装します……

Oh, I thought so too... I'll do that.

**Comment by xia-sava** [comment]
https://github.com/xia-sava/Monochromer/commit/a7ec6bdb2018d7be8799dde89127b50a4f1c4d8e implements this function. Thanks!
実装しました．ありがとうございます！

**Comment by grahamperrin** [comment]
Thanks @xia-sava! 

### Context sensitivity

A minor cosmetic issue. when monochrome is effective, pointing at the button should not say: 

> Monochrome this page

Instead, maybe: 

> Restore colour

**Comment by xia-sava** [comment]
Now, v0.3.0, icon and label is changed according to monochroming status. Thanks!

**Comment by grahamperrin** [comment]
Confirmed, all good. Thanks again!
