### ISSUE TITLE
Unexpected change of layout at www.ianbicking.org

### ISSUE THREAD

**Issue by grahamperrin** [xia-sava/Monochromer#2]
http://www.ianbicking.org/blog/2014/09/professional-transitions.html for example. 

Before: 

![2018-11-24 10 09 09 waterfox](https://user-images.githubusercontent.com/192271/48966936-433bdc80-efd1-11e8-82ab-6197b2ae36b9.png)

After: 

![2018-11-24 10 09 34 waterfox](https://user-images.githubusercontent.com/192271/48966940-4b941780-efd1-11e8-99d6-1eba9c1eed42.png)

– note the overlapping texts towards the right hand side of the page.

**Comment by xia-sava** [comment]
https://github.com/xia-sava/Monochromer/commit/3278da2d2f10c482d09f1330dda65e9e477b6d25 refines monochrome-conversion method, it probably solves this problem. Please confirm with Ver.0.2.0 (already published on AMO).

**Comment by grahamperrin** [comment]
Fix confirmed, thanks! 

![2018-11-25 02 56 43 waterfox](https://user-images.githubusercontent.com/192271/48974943-fe11bc00-f05d-11e8-80e5-8060f4a3c20d.png)

(The colours in the Diigo floating note are expected. It pops up after Monochromer is applied.)

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/addon/monochromer/reviews/1240872/ updated and upgraded from four stars, to five. Apologies for the late follow-up.
